package model

// Fielder describes any type that can expose its schema and
// writable pointers. It is the shared contract between orm (database),
// form (UI), and json layers, replacing runtime reflection.
//
// Implementations are generated by code generators — never written by hand.
//
// Contract:
//   - Schema() and Pointers() MUST return slices of the same length.
//   - The i-th element in each slice corresponds to the same struct field.
//   - Pointers() returns pointers to fields for reading (dereference) and writing (scan/sync).
type Fielder interface {
	Schema() []Field
	Pointers() []any
}

// FielderSlice is implemented by generated code to allow
// iteration over a slice of structs without reflection.
type FielderSlice interface {
	Fielder
	Len() int
	At(i int) Fielder
	Append() Fielder
}

// Validator is implemented by types that can self-validate.
// Generated by ormc: func (m *X) Validate(action byte) error { return model.ValidateFields(action, m) }
// Used by form, json.Decode, and orm pre-insert to enforce data integrity.
type Validator interface {
	Validate(action byte) error
}

// ModuleNaming is the minimal identity contract shared across the ecosystem: a
// stable model name used as route key, nav hash and DOM id. Consumers that need only
// identity (routing, layout shells) embed this; data models embed the richer Model.
type ModuleNaming interface {
	ModelName() string
}

// Model is the full contract that ormc generates for every domain record: it knows its
// schema and writable pointers (Fielder), its stable name (ModuleNaming), and how to
// travel over the wire in both directions (Encodable, Decodable).
//
// It is THE type to name at any boundary that handles a domain record — a form that
// renders it, a Caller that ships it, an ORM that scans it. Consumers MUST NOT declare
// local intersections of the atoms below; if a boundary needs a combination that this
// package does not name, that is a defect HERE, not in the consumer.
//
// Implementations are generated by ormc — never written by hand.
type Model interface {
	Fielder      // Schema() + Pointers()   → form, orm
	ModuleNaming // ModelName()             → routing, RBAC resource
	Encodable    // EncodeFields() + IsNil() → to the wire
	Decodable    // DecodeFields() + IsNil() → from the wire
}

// ModelSlice is the wire-decodable counterpart of FielderSlice: a list result a
// Caller can decode a Call response into, row by row. It is THE type to name at any
// boundary that lists domain records over the wire (a Presenter's list operation, a
// Caller consumer) — do not declare a local intersection of FielderSlice+Decodable.
type ModelSlice interface {
	FielderSlice
	Decodable
}

// SafeFields combines schema access with validation.
// Handlers that receive user input should accept SafeFields
// to enforce compile-time validation guarantees.
type SafeFields interface {
	Fielder
	Validator
}

// IDGenerator mints a new primary-key value for a record about to be created.
// It is THE contract to name at any boundary that needs identity generation — a
// domain module creating a record, a composition root wiring one in. Consumers
// MUST NOT construct a concrete generator (e.g. unixid.NewUnixID) inside a
// reusable module: that hardcodes an implementation the module should not know
// about. Accept IDGenerator instead and let the composition root inject it.
//
// Implementations: webtyp.com/unixid (time-sortable, collision-safe
// under concurrent callers). A test double can be a func literal satisfying
// this single-method interface.
type IDGenerator interface {
	NewID() string
}
